spring:
  datasource:
    password: admin 
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/focus
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
